apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: taskforge, namespace: argocd}
spec:
  project: default
  source:
    repoURL: https://github.com/shraddhamankar016-cell/taskforge.git
    targetRevision: main
    path: helm/taskforge
  destination: {server: https://kubernetes.default.svc, namespace: taskforge}
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
